export const ON_CHANGE_USERNAME = 'ON_CHANGE_USERNAME'
export const ON_CHANGE_PASSWORD = 'ON_CHANGE_PASSWORD'
export const ON_CHANGE_VERIFYCODE = 'ON_CHANGE_VERIFYCODE';
export const ON_CHANGE_PHONE = 'ON_CHANGE_PHONE';
export const SET_TOKEN = 'SET_TOKEN'
